baseURL: "https://beastion.biz.id/"
languageCode: "en-us"
title: "beastion.biz.id"
canonifyURLs: true

permalinks:
  articles: "/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - Sitemap
  page:
    - HTML
    - Sitemap
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  term:
    - HTML
    - RSS

services:
  rss:
    limit: 50

taxonomies:
  category: "categories"
  tag: "tags"

params:
  description: "Your #1 source for breaking Sports news, live scores, transfer rumors (Fabrizio Romano), and tactical analysis for Premier League, La Liga, & Champions League."
  defaultImage: "/images/default-football.jpg"
  author:
    name: "beastion.biz.id Team"
    email: "contact@Sportdaily.com"
